const unitWeight = ['LB','KG','GR','Hundredths Pounds','MG','Tons','OZ'];
const unitWattage = ['Watt','Hours','Picowatts','Milliamp Hours', 'Milliwatts', 'Microwatts','Kilowatt Hours','Kilowatts','Nanowatts','Watts'];
const unitMemory = ['MB','GB','TB'];
const unitLength = ['FT','CM','MM','DM','Picometre','µM','M','Miles','Yards','Mils','IN','Nanometre','Hundredths-Inches','Kilometres','Angstrom'];
const unitCapacity = ['liters', 'Quarts' ,'Fluid Ounces', 'ounces', 'milliliters', 'Cubic Feet', 'Microliters', 'Cubic Centimeters' ,'Pints' ,'Gallons', 'pounds' ,'Tons','Cubic Inches', 'kilograms'];
const unitOptical = ['diopters'];
const unitLensPower = ['milliwatts','microwatts','horsepower','nanowatts','picowatts','watts'];
const unitGraduation = ['Feet' ,'centimeters', 'millimeters', 'Decimeters', 'Pints', 'Inches', 'gallons', 'Cubic Meters', 'nanometer' ,'Hundredths-Inches' ,'Ten Thousandths Inches', 'Cubic Centimeters', 'Quarts', 'picometer', 'milliliters', 'Kilometers', 'Fluid Ounces', 'Cubic Yards', 'Meters', 'micrometer', 'Cubic Inches', 'Imperial Gallons', 'Yards', 'Cubic Feet', 'Miles', 'Thousandths Inches', 'liters', 'Angstrom'];

export const allProperties = {
    'Electronics':{
        'Audio' : [
            {'name':'Color','type':'text','example':'Red,Blue', 'variationAllowed':true}
        ],
        'Camera and Camcorder' : [
            {'name':'Size','type':'text','example':'Small', 'variationAllowed':true},
            {'name':'Compact','type':'text','example':'', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'Small', 'variationAllowed':true},
            {'name':'Full-Size','type':'text','example':'Small', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'Small', 'variationAllowed':true},
            {'name':'stylename','type':'text','example':'Small', 'variationAllowed':true}
        ],
        'Computer Peripheral' : [
            {'name':'Size','type':'text','example':'', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
            {'name':'stylename','type':'text','example':'', 'variationAllowed':true}
        ],

        'Desktop and Laptop' : [
            {'name':'Item Weight','unit':unitWeight,'type':'text','example':'', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'', 'variationAllowed':true},
            {'name':'Wattage','unit':unitWattage,'type':'text','example':'', 'variationAllowed':true},
            {'name':'Voltage','type':'text','example':'', 'variationAllowed':true},
            {'name':'Team Name','type':'text','example':'', 'variationAllowed':true},
            {'name':'Item Display weight','unit':unitWeight,'type':'text','example':'', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
            {'name':'Memory Storage Capacity','unit':unitMemory,'type':'text','example':'', 'variationAllowed':true},
            {'name':'Model Number','type':'text','example':'', 'variationAllowed':true},
            {'name':'Product Grade','type':'text','example':'', 'variationAllowed':true},
            {'name':'Hardware Platform','type':'text','example':'', 'variationAllowed':true},
            {'name':'Hard Drive Size','unit':unitMemory,'type':'text','example':'', 'variationAllowed':true},
            {'name':'Screen Size','unit':unitLength,'type':'text','example':'', 'variationAllowed':true},
        ],
        'Earphone' : [
            {'name':'Size','type':'text','example':'', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
            {'name':'Edition','type':'text','example':'', 'variationAllowed':true},
        ],
        'Gaming' : [
            {'name':'Item Weight','type':'text','example':'', 'variationAllowed':true},
            {'name':'Number of Items','type':'numberer','example':'', 'variationAllowed':true},
            {'name':'Wattage','unit':unitWattage,'type':'text','example':'', 'variationAllowed':true},
            {'name':'Model Number','type':'number','example':'', 'variationAllowed':true},
        ],
        'Headphone' : [
            {'name':'Size','type':'text','example':'', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
        ],
        'Mobile Phone' : [
            {'name':'Memory','unit':unitMemory,'type':'text','example':'', 'variationAllowed':true},
            {'name':'Item Weight','unit':unitWeight,'type':'text','example':'', 'variationAllowed':true},
            {'name':'Number of Items','type':'numberer','example':'', 'variationAllowed':true},
            {'name':'Team Name','type':'text','example':'', 'variationAllowed':true},
            {'name':'Model Number','type':'number','example':'', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
            {'name':'Product Grade','type':'text','example':'', 'variationAllowed':true},
            {'name':'Screen Size Unit Of Measure','unit':unitLength,'type':'text','example':'', 'variationAllowed':true},
        ],
        'Mobile Accessories' : [
            {'name':'Pattern','type':'text','example':'', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
            {'name':'Number of Items','type':'numberer','example':'', 'variationAllowed':true},
            {'name':'Material Type','type':'text','example':'', 'variationAllowed':true},
            {'name':'Item Weight','unit':unitWeight,'type':'text','example':'', 'variationAllowed':true},
            {'name':'Thickness','unit':unitLength,'type':'text','example':'', 'variationAllowed':true},
            {'name':'Model Number','type':'number','example':'', 'variationAllowed':true},
            {'name':'Screen Size Unit Of MeasureScreen','unit':unitLength,'type':'text','example':'', 'variationAllowed':true},
        ],
        'Safety Security' : [
            {'name':'Style Name','type':'text','example':'', 'variationAllowed':true},
            {'name':'Size','type':'text','example':'', 'variationAllowed':true},
            {'name':'Number of Items','type':'numberer','example':'', 'variationAllowed':true},
            {'name':'Item Form','type':'text','example':'', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
            {'name':'Pattern','type':'text','example':'', 'variationAllowed':true},
            {'name':'Display Weight','unit':unitWeight,'type':'text','example':'', 'variationAllowed':true},
        ],
        'Smart Watches' : [
            {'name':'Size','type':'text','example':'', 'variationAllowed':true},
            {'name':'Style','type':'text','example':'', 'variationAllowed':true},
            {'name':'Number of Items','type':'numberer','example':'', 'variationAllowed':true},
            {'name':'Item Form','type':'text','example':'', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
            {'name':'DriveMemory Storage Capacity','unit':unitMemory,'type':'text','example':'', 'variationAllowed':true},
            {'name':'Model Number','unit':unitWeight,'type':'text','example':'', 'variationAllowed':true},
            {'name':'Manufacturer Part Number','type':'text','example':'', 'variationAllowed':true},
            {'name':'Unit Count','type':'text','example':'', 'variationAllowed':true},
            {'name':'Band Colour','type':'text','example':'', 'variationAllowed':true},
            {'name':'Shape','type':'text','example':'', 'variationAllowed':true},
            {'name':'Screen Size Unit Of MeasureScreen','unit':unitLength,'type':'text','example':'', 'variationAllowed':true},
        ],
        'Speaker' : [
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
        ],
        'Television' : [
            {'name':'Style','type':'text','example':'', 'variationAllowed':true},
            {'name':'DriveMemory Storage Capacity','unit':unitMemory,'type':'text','example':'', 'variationAllowed':true},
            {'name':'Item Weight','unit':unitWeight,'type':'text','example':'', 'variationAllowed':true},
            {'name':'Number of Items','type':'numberer','example':'', 'variationAllowed':true},
            {'name':'Model Number','type':'text','example':'', 'variationAllowed':true},
            {'name':'Manufacturer Part Number','type':'text','example':'', 'variationAllowed':true},
            {'name':'Wattage','unit':unitWattage,'type':'text','example':'', 'variationAllowed':true},
            {'name':'Unit Count','type':'text','example':'', 'variationAllowed':true},
            {'name':'Voltage','type':'text','example':'', 'variationAllowed':true},
            {'name':'Team Name','type':'text','example':'', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
            {'name':'Display Size','type':'text','example':'', 'variationAllowed':true},
        ],
        'Video' : [
            {'name':'Style Name','type':'text','example':'', 'variationAllowed':true},
            {'name':'Size','type':'text','example':'', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
        ],
        'Air Conditioning and Air Cleaners' : [
            {'name':'Style','type':'text','example':'', 'variationAllowed':true},
            {'name':'Size','type':'text','example':'', 'variationAllowed':true},
            {'name':'Number of Items','type':'numberer','example':'', 'variationAllowed':true},
            {'name':'Item Weight','unit':unitWeight,'type':'text','example':'', 'variationAllowed':true},
            {'name':'Wattage','unit':unitWattage,'type':'text','example':'', 'variationAllowed':true},
            {'name':'Voltage','type':'text','example':'', 'variationAllowed':true},
            {'name':'Unit Count','type':'text','example':'', 'variationAllowed':true},
            {'name':'Model','type':'text','example':'', 'variationAllowed':true},
        ],
        'Health, Home and Personal Care' : [
            {'name':'Item Display Length','type':'text','example':'', 'variationAllowed':true},
            {'name':'Size','type':'text','example':'', 'variationAllowed':true},
            {'name':'Number of Items','type':'numberer','example':'', 'variationAllowed':true},
            {'name':'Material Type','type':'text','example':'', 'variationAllowed':true},
            {'name':'Package Type','type':'text','example':'', 'variationAllowed':true},
            {'name':'Item Display','type':'text','example':'', 'variationAllowed':true},
            {'name':'Width','type':'text','example':'','unit':unitLength},
            {'name':'Patter','type':'text','example':'', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
            {'name':'Item Display Height','type':'text','example':'', 'variationAllowed':true},
            {'name':'Item Display Diameter','type':'text','example':'', 'variationAllowed':true},
            {'name':'Item Weight','type':'text','example':'', 'variationAllowed':true},
            {'name':'model','type':'text','example':'', 'variationAllowed':true},
            {'name':'Manufacturer Part Number','type':'number','example':'', 'variationAllowed':true},
            {'name':'Wattage','type':'text','example':'','unit':unitWattage},
            {'name':'Unit Count','type':'text','example':'', 'variationAllowed':true},
            {'name':'Shape','type':'text','example':'', 'variationAllowed':true},
        ],
        'Heaters' : [
            {'name':'Size','type':'text','example':'', 'variationAllowed':true},
            {'name':'Style','type':'text','example':'', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'', 'variationAllowed':true},
            {'name':'Item Weight','type':'text','example':'','unit':unitWeight},
            {'name':'Wattage','type':'text','example':'','unit':unitWattage},
            {'name':'Voltage','type':'text','example':'', 'variationAllowed':true},
            {'name':'model','type':'text','example':'', 'variationAllowed':true},
            {'name':'Unit Count','type':'number','example':'', 'variationAllowed':true},
        ],
        'Kitchen Appliances' : [
            {'name':'Size','type':'text','example':'Large', 'variationAllowed':true},
            {'name':'Material Type','type':'text','example':'Steel', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'2,3', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
            {'name':'Item Weight','type':'text','example':'3.3','unit':unitWeight},
            {'name':'Unit Count','type':'number','example':'1', 'variationAllowed':true},
        ],
        'Lighting & Electric Fans' : [
            {'name':'Size','type':'text','example':'Large', 'variationAllowed':true},
            {'name':'Style','type':'text','example':'Modern', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Item Weight','type':'text','example':'','unit':unitWeight},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
            {'name':'Material Type','type':'text','example':'Steel', 'variationAllowed':true},
            {'name':'Manufacturer Part Number','type':'text','example':'', 'variationAllowed':true},
            {'name':'Model','type':'text','example':'', 'variationAllowed':true},
            {'name':'Wattage','type':'text','example':'','unit':unitWattage},
            {'name':'Unit Count','type':'number','example':'5', 'variationAllowed':true},
            {'name':'Voltage','type':'number','example':'5', 'variationAllowed':true},
        ],
        'Refrigerators and Freezers' : [
            {'name':'Size','type':'text','example':'', 'variationAllowed':true},
            {'name':'Style','type':'text','example':'', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'', 'variationAllowed':true},
            {'name':'Item Weight','type':'text','example':'4','unit':unitWeight},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
            {'name':'Material Type','type':'text','example':'', 'variationAllowed':true},
            {'name':'Model','type':'text','example':'', 'variationAllowed':true},
            {'name':'Capacity','type':'text','example':'','unit':unitCapacity},
            {'name':'Manufacturer Part Number','type':'text','example':'', 'variationAllowed':true},
            {'name':'Model','type':'text','example':'LG12', 'variationAllowed':true},
        ],
        'Vacuum Cleaners' : [
            {'name':'Size','type':'text','example':'', 'variationAllowed':true},
            {'name':'Style','type':'text','example':'', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'', 'variationAllowed':true},
            {'name':'Item Weight','type':'text','example':'4','unit':unitWeight},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
            {'name':'Material Type','type':'text','example':'', 'variationAllowed':true},
            {'name':'Model','type':'text','example':'', 'variationAllowed':true},
            {'name':'Capacity','type':'text','example':'','unit':unitCapacity},
            {'name':'Manufacturer Part Number','type':'text','example':'', 'variationAllowed':true},
            {'name':'Model','type':'text','example':'LG12', 'variationAllowed':true},
        ],
        'Washing Machines and Accessories' : [
            {'name':'Size','type':'text','example':'', 'variationAllowed':true},
            {'name':'Style','type':'text','example':'', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'', 'variationAllowed':true},
            {'name':'Item Weight','type':'text','example':'4','unit':unitWeight},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
            {'name':'Material Type','type':'text','example':'', 'variationAllowed':true},
            {'name':'Model','type':'text','example':'', 'variationAllowed':true},
            {'name':'Capacity','type':'text','example':'','unit':unitCapacity},
            {'name':'Manufacturer Part Number','type':'text','example':'', 'variationAllowed':true},
            {'name':'Model','type':'text','example':'LG12', 'variationAllowed':true},
        ],
        'Water Purifiers and Coolers' : [
            {'name':'Size','type':'text','example':'', 'variationAllowed':true},
            {'name':'Graduation Interval','type':'text','example':'', 'unit':unitGraduation},
            {'name':'Style','type':'text','example':'', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'', 'variationAllowed':true},
            {'name':'Item Weight','type':'text','example':'4','unit':unitWeight},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
            {'name':'Material Type','type':'text','example':'', 'variationAllowed':true},
            {'name':'Model','type':'text','example':'', 'variationAllowed':true},
            {'name':'Capacity','type':'text','example':'','unit':unitCapacity},
            {'name':'Manufacturer Part Number','type':'text','example':'', 'variationAllowed':true},
            {'name':'Model','type':'text','example':'LG12', 'variationAllowed':true},
        ]
    },
    'Grocery':{
        'Fruits and Vegetables':[
        ],
        'Masala & Seasoning':[
        ],
        'Oil & Ghee':[
        ],
        'Gourmet & World Foods':[
        ],
        'Foodgrains':[
        ],
        'Eggs, Meat & Fish':[
        ],
        'Cleaning & Household':[
            {'name':'Size','type':'text','example':'', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
            {'name':'Style','type':'text','example':'', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Material Type','type':'text','example':'plastic', 'variationAllowed':true},
            {'name':'Width Range','type':'text','example':'','unit':unitLength},
            {'name':'Length Range','type':'text','example':'','unit':unitLength},
        ],
        'Beverages':[
            {'name':'Size','type':'text','example':'', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
            {'name':'stylename','type':'text','example':'', 'variationAllowed':true}
        ],
        'Beauty & Hygiene':[
            {'name':'Size','type':'text','example':'', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
            {'name':'Scent','type':'text','example':'rose', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'6', 'variationAllowed':true},
            {'name':'PPU Count','type':'text','example':'1', 'variationAllowed':true},
            {'name':'Item Form','type':'text','example':'Cream', 'variationAllowed':true},
            {'name':'Model','type':'text','example':'AB12', 'variationAllowed':true},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
        ],
        'Bakery, Cakes & Dairy':[
            {'name':'Size','type':'text','example':'small', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
            {'name':'Material Type','type':'text','example':'floor', 'variationAllowed':true},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Unit Count','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Model','type':'text','example':'AB-12', 'variationAllowed':true},
            {'name':'Shape','type':'text','example':'Round', 'variationAllowed':true},
            {'name':'Capacity','type':'float','example':'4','unit':unitCapacity},
            {'name':'Manufacturer Part Number','type':'float','example':'A-112', 'variationAllowed':true},
        ],
        'Kitchen Accessories':[
            {'name':'Size','type':'text','example':'small', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
            {'name':'Material Type','type':'text','example':'Steel', 'variationAllowed':true},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Unit Count','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Model','type':'text','example':'AB-12', 'variationAllowed':true},
            {'name':'Pattern','type':'text','example':'', 'variationAllowed':true},
        ],
        'Baby Care':[
            {'name':'Scent','type':'text','example':'rose', 'variationAllowed':true},
            {'name':'Scent','type':'text','example':'rose', 'variationAllowed':true},
            {'name':'Style','type':'text','example':'modern', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Material Type','type':'text','example':'rose', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
            {'name':'PPU Count','type':'text','example':'1', 'variationAllowed':true},
            {'name':'Item Form','type':'text','example':'Cream', 'variationAllowed':true},
            {'name':'Pattern','type':'text','example':'', 'variationAllowed':true},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Model','type':'text','example':'AB-12', 'variationAllowed':true},
        ],
        'Snacks & Branded Foods':[
        ],
        'Pet Care':[
            {'name':'Scent Name','type':'text','example':'mild', 'variationAllowed':true},
            {'name':'Flavor','type':'text','example':'', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'brown', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'6', 'variationAllowed':true},
        ],
        'Stationery':[
            {'name':'Size','type':'text','example':'A4,6x4', 'variationAllowed':true},
            {'name':'Paper Size','type':'text','example':'', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
            {'name':'Line Size','type':'text','example':'', 'variationAllowed':true} ,
            {'name':'Maximum Size','type':'text','example':'', 'variationAllowed':true} ,
        ],
    },
    'Home Decor':{
        'Home Decor':[
            {'name':'Size','type':'text','example':'small', 'variationAllowed':true},
            {'name':'Style','type':'text','example':'modern', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Material Type','type':'text','example':'wood', 'variationAllowed':true},
            {'name':'Pattern','type':'text','example':'Sripped', 'variationAllowed':true},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Model','type':'text','example':'AB-12', 'variationAllowed':true},
            {'name':'Manufacturer Part Number','type':'float','example':'A-112', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
            {'name':'Wattage','type':'text','example':'', 'unit':unitWattage},
            {'name':'VoltageColor','type':'text','example':'6', 'variationAllowed':true},
            {'name':'Unit Count','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Shape','type':'text','example':'Round', 'variationAllowed':true},
        ],
        'Home Furnishings':[
            {'name':'Size','type':'text','example':'small', 'variationAllowed':true},
            {'name':'Style','type':'text','example':'modern', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
            {'name':'Material Type','type':'text','example':'wood', 'variationAllowed':true},
            {'name':'Pattern','type':'text','example':'Sripped', 'variationAllowed':true},
            {'name':'Display Weight','type':'text','example':'5','unit':unitWeight},
        ],
        'Furniture':[
            {'name':'Size','type':'text','example':'small', 'variationAllowed':true},
            {'name':'Style','type':'text','example':'modern', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Material Type','type':'text','example':'wood', 'variationAllowed':true},
            {'name':'Pattern','type':'text','example':'Sripped', 'variationAllowed':true},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Unit Count','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Model','type':'text','example':'AB-12', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
            {'name':'Team Name','type':'text','example':'chennai super kings', 'variationAllowed':true},
            {'name':'Shape','type':'text','example':'Round', 'variationAllowed':true},
        ],
        'Garden and Outdoor Products':[
            {'name':'Material Type','type':'text','example':'wood', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
        ],
        'Home Improvement':[
            {'name':'Size','type':'text','example':'small', 'variationAllowed':true},
            {'name':'Style','type':'text','example':'modern', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
        ],
        'Cookware and Dining':[
            {'name':'Size','type':'text','example':'small', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Material Type','type':'text','example':'wood', 'variationAllowed':true},
            {'name':'Pattern','type':'text','example':'Sripped', 'variationAllowed':true},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Unit Count','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Model','type':'text','example':'AB-12', 'variationAllowed':true},
            {'name':'Shape','type':'text','example':'Round', 'variationAllowed':true},
            {'name':'Capacity','type':'text','example':'', 'unit':unitCapacity},
            {'name':'Manufacturer Part Number','type':'float','example':'A-112', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
        ],
        'Storage and Organisation':[
            {'name':'Size','type':'text','example':'small', 'variationAllowed':true},
            {'name':'Style','type':'text','example':'modern', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Material Type','type':'text','example':'wood', 'variationAllowed':true},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Unit Count','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Team Name','type':'text','example':'Lions', 'variationAllowed':true},
            {'name':'Model','type':'text','example':'AB-12', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
            {'name':'Shape','type':'text','example':'Round', 'variationAllowed':true},
        ],
    },
    'Health and Wellness':{
        'Pain Relieving Ointments':[
            {'name':'Style','type':'text','example':'Art Deco', 'variationAllowed':true},
            {'name':'Material Type','type':'text','example':'Metal', 'variationAllowed':true},
            {'name':'Size','type':'text','example':'Large', 'variationAllowed':true},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Model','type':'text','example':'AB-12', 'variationAllowed':true},
            {'name':'Manufacturer Part Number','type':'float','example':'A-112', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'Grey', 'variationAllowed':true},
            {'name':'PPU Count','type':'number','example':'6', 'variationAllowed':true},
        ],
        'Nutrition and Supplements':[
            {'name':'Flavour','type':'text','example':'Strawberry', 'variationAllowed':true},
            {'name':'Size','type':'text','example':'small', 'variationAllowed':true},
            {'name':'Scent','type':'text','example':'musk', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
            {'name':'PPU Count','type':'text','example':'6', 'variationAllowed':true},
            {'name':'Model','type':'text','example':'EEPL 456', 'variationAllowed':true},
        ],
        'Personal and Baby Care':[
            {'name':'Scent','type':'text','example':'musk', 'variationAllowed':true},
            {'name':'Size','type':'text','example':'small', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Itrm Form','type':'text','example':'Cream', 'variationAllowed':true},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'PPU Count','type':'text','example':'6', 'variationAllowed':true},
            {'name':'Model','type':'text','example':'EEPL 456', 'variationAllowed':true},
        ],
        'Sexual Wellness':[
            {'name':'Scent','type':'text','example':'musk', 'variationAllowed':true},
            {'name':'Size','type':'text','example':'small', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Item Form','type':'text','example':'Cream', 'variationAllowed':true},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'PPU Count','type':'text','example':'6', 'variationAllowed':true},
            {'name':'Model','type':'text','example':'EEPL 456', 'variationAllowed':true},
        ],
        'Gastric and Other Concerns':[
            {'name':'Flavour','type':'text','example':'Strawberry', 'variationAllowed':true},
            {'name':'Size','type':'text','example':'small', 'variationAllowed':true},
            {'name':'Scent','type':'text','example':'musk', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
            {'name':'PPU Count','type':'text','example':'6', 'variationAllowed':true},
            {'name':'Model','type':'text','example':'EEPL 456', 'variationAllowed':true},
        ],
        'Covid Essentials':[
            {'name':'Size','type':'text','example':'small', 'variationAllowed':true},
            {'name':'Style','type':'text','example':'Cape Cod', 'variationAllowed':true},
            {'name':'Material Type','type':'number','example':'Cotton', 'variationAllowed':true},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Model','type':'text','example':'EEPL 456', 'variationAllowed':true},
            {'name':'Manufacturer Part Number','type':'text','example':'RTC 54', 'variationAllowed':true},
            {'name':'Unit Count','type':'number','example':'4', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
            {'name':'Team Name','type':'text','example':'Royal', 'variationAllowed':true},
            {'name':'Item Shape','type':'text','example':'Molded cup', 'variationAllowed':true},
        ],
        'Diabetes Control':[
            {'name':'Flavour','type':'text','example':'Strawberry', 'variationAllowed':true},
            {'name':'Size','type':'text','example':'small', 'variationAllowed':true},
            {'name':'Scent','type':'text','example':'musk', 'variationAllowed':true},
            {'name':'Item Package Quantity','type':'number','example':'6', 'variationAllowed':true},
        ],
        'Health Devices':[
            {'name':'Thickness','type':'text','example':'11', 'variationAllowed':true},
            {'name':'Material Type','type':'text','example':'Steel', 'variationAllowed':true},
            {'name':'Model','type':'text','example':'EEPL 456', 'variationAllowed':true},
            {'name':'Shape','type':'text','example':'Round', 'variationAllowed':true},
            {'name':'Capacity','type':'text','example':'5','unit':unitCapacity},
            {'name':'Number of Items','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Manufacturer Part Number','type':'text','example':'RTC 54', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
        ],
    },
    'Beauty & Personal Care':{
        'Bath & Body':[
            {'name':'Size','type':'text','example':'small', 'variationAllowed':true},
            {'name':'Scent','type':'text','example':'Musk', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
            {'name':'Item Form','type':'text','example':'Cream', 'variationAllowed':true},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Model','type':'text','example':'AB-12', 'variationAllowed':false},
            {'name':'PPU Count','type':'text','example':'6', 'variationAllowed':true},
        ],
        'Feminine Care':[
            {'name':'Size','type':'text','example':'small', 'variationAllowed':true},
            {'name':'Style','type':'text','example':'modern', 'variationAllowed':true},
            {'name':'Scent','type':'text','example':'musk', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Material Type','type':'text','example':'wood', 'variationAllowed':true},
            {'name':'Item Form','type':'text','example':'Cream', 'variationAllowed':true},
            {'name':'Optical Power','type':'text','example':'5','unit':unitOptical},
            {'name':'Color','type':'text','example':'Blue', 'variationAllowed':true},
            {'name':'Base Curve Radius','type':'text','example':'5','unit':unitLength},
            {'name':'Item Diameter','type':'text','example':'5', 'variationAllowed':true},
            {'name':'PPU Count','type':'text','example':'6', 'variationAllowed':true},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Flavour','type':'text','example':'', 'variationAllowed':true},
            {'name':'Model Number','type':'text','example':'ER 44', 'variationAllowed':true},
            {'name':'Lens Addition Power','type':'text','example':'','unit':unitLensPower},
            {'name':'Cylinder Correction','type':'text','example':'', 'variationAllowed':true},
            {'name':'Cylinder Axis','type':'text','example':'Sripped', 'variationAllowed':true},
        ],
        'Fragrance':[
            {'name':'Style Name','type':'text','example':'Mision', 'variationAllowed':true},
            {'name':'Scent','type':'text','example':'Rose', 'variationAllowed':true},
            {'name':'Size','type':'text','example':'small', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Item Form','type':'text','example':'Gas', 'variationAllowed':true},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Model Number','type':'text','example':'TTYU 6', 'variationAllowed':true},
            {'name':'Manufacturer Part Number','type':'text','example':'TTYU 6', 'variationAllowed':true},
            {'name':'Unit Count','type':'number','example':'4', 'variationAllowed':true},
            {'name':'Volume','type':'text','example':'AB-12', 'unit':unitGraduation},
        ],
        'Hair Care':[
            {'name':'Scent Name','type':'text','example':'Spice', 'variationAllowed':true},
            {'name':'Size','type':'text','example':'small', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'Red', 'variationAllowed':true},
            {'name':'Item Form','type':'text','example':'Cream', 'variationAllowed':true},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Model Number','type':'text','example':'TTYU 6', 'variationAllowed':true},
            {'name':'PPU Count','type':'text','example':'6', 'variationAllowed':true},
        ],
        'Make Up':[
            {'name':'Scent','type':'text','example':'Spice', 'variationAllowed':true},
            {'name':'Size','type':'text','example':'small', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'Red', 'variationAllowed':true},
            {'name':'Item Form','type':'text','example':'Cream', 'variationAllowed':true},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Model Number','type':'text','example':'TTYU 6', 'variationAllowed':true},
            {'name':'PPU Count','type':'text','example':'6', 'variationAllowed':true},
        ],
        "Men's Grooming":[
            {'name':'Scent','type':'text','example':'Spice', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'Red', 'variationAllowed':true},
            {'name':'Size','type':  'text','example':'small', 'variationAllowed':true},
            {'name':'Model Number','type':'text','example':'TTYU 6', 'variationAllowed':true},
            {'name':'PPU Count','type':'text','example':'6', 'variationAllowed':true},
            {'name':'Team Name','type':'number','example':'Royal', 'variationAllowed':true}
        ],
        'Oral Care':[
            {'name':'Flavour','type':'text','example':'Mint', 'variationAllowed':true},
            {'name':'Size','type':'text','example':'small', 'variationAllowed':true},
            {'name':'Scent','type':'text','example':'Musk', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'Red', 'variationAllowed':true},
            {'name':'Item Form','type':'text','example':'Cream', 'variationAllowed':true},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'PPU Count','type':'text','example':'6', 'variationAllowed':true},
            {'name':'Unit Count','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Model','type':'text','example':'AB-12', 'variationAllowed':true},
        ],
        'Skin Care':[
            {'name':'Scent','type':'text','example':'Musk', 'variationAllowed':true},
            {'name':'Size','type':'text','example':'small', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Item Form','type':'text','example':'Cream', 'variationAllowed':true},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'PPU Count','type':'text','example':'6', 'variationAllowed':true},
            {'name':'Model','type':'text','example':'AB-12', 'variationAllowed':true},
        ],
        'Maternity Care':[
            {'name':'Size','type':'text','example':'small', 'variationAllowed':true},
            {'name':'Style','type':'text','example':'modern', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Material Type','type':'text','example':'wood', 'variationAllowed':true},
            {'name':'Color','type':'text','example':'', 'variationAllowed':true},
        ],
        'Nursing & Feeding':[
            {'name':'Size','type':'text','example':'Small', 'variationAllowed':true},
            {'name':'Shape','type':'text','example':'Round', 'variationAllowed':true},
            {'name':'Pattern','type':'text','example':'Striped', 'variationAllowed':true},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Unit Count','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Model','type':'text','example':'AB-12', 'variationAllowed':true},
        ],
        'Sexual Wellness & Sensuality':[
            {'name':'Scent','type':'text','example':'musk', 'variationAllowed':true},
            {'name':'Size','type':'text','example':'small', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Item Form','type':'text','example':'Cream', 'variationAllowed':true},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'PPU Count','type':'text','example':'6', 'variationAllowed':true},
            {'name':'Model','type':'text','example':'EEPL 456', 'variationAllowed':true},
        ],
        'Tools & Accessories':[
            {'name':'Size','type':'text','example':'small', 'variationAllowed':true},
            {'name':'Style','type':'text','example':'modern', 'variationAllowed':true},
            {'name':'Number of Items','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Material Type','type':'text','example':'wood', 'variationAllowed':true},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Model','type':'text','example':'AB-12', 'variationAllowed':true},
            {'name':'Unit Count','type':'number','example':'6', 'variationAllowed':true},
            {'name':'Item Shape','type':'text','example':'Round', 'variationAllowed':true},
            {'name':'Manufacturer Part Number','type':'text','example':'ABT 243', 'variationAllowed':true},
        ],
    },
    'Food and Beverages':{

    }
};

