export const MAX_STRING_LENGTH = 255;
export const MAX_STRING_LENGTH_50 = 50;
export const MAX_STRING_LENGTH_14 = 14;
export const MAX_STRING_LENGTH_10 = 10;
export const MAX_STRING_LENGTH_12 = 12;
export const MAX_STRING_LENGTH_3 = 3;
export const MAX_STRING_LENGTH_6 = 6;
export const MAX_STRING_LENGTH_8 = 8;
export const MAX_STRING_LENGTH_13 = 13;

export const PRODUCT_CATEGORY = {
    "Grocery": "Grocery",
    "F&B": "F&B",
    "Home & Decor": "Home & Decor",
    "Health & Wellness": "Health & Wellness",
    "Electronics": "Electronics",
    "Beauty & Personal Care": "Beauty & Personal Care",
    "Fashion": "Fashion",
}

export const PRODUCT_SUBCATEGORY = {
    "Grocery": [
        {value: 'Fruits and Vegetables', key: 'Fruits and Vegetables', protocolKey: "@ondc/org/mandatory_reqs_veggies_fruits"},
        {value: 'Masala & Seasoning', key: 'Masala & Seasoning', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: 'Oil & Ghee', key: 'Oil & Ghee', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: 'Gourmet & World Foods', key: 'Gourmet & World Foods', protocolKey: "@ondc/org/statutory_reqs_prepackaged_food"},
        {value: 'Foodgrains', key: 'Foodgrains', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: 'Eggs, Meat & Fish', key: 'Eggs, Meat & Fish', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: 'Cleaning & Household', key: 'Cleaning & Household', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: 'Beverages', key: 'Beverages', protocolKey: "@ondc/org/statutory_reqs_prepackaged_food"},
        {value: 'Beauty & Hygiene', key: 'Beauty & Hygiene', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: 'Bakery, Cakes & Dairy', key: 'Bakery, Cakes & Dairy', protocolKey: "@ondc/org/statutory_reqs_prepackaged_food"},
        {value: 'Kitchen Accessories', key: 'Kitchen Accessories', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: 'Baby Care', key: 'Baby Care', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: 'Snacks & Branded Foods', key: 'Snacks & Branded Foods', protocolKey: "@ondc/org/statutory_reqs_prepackaged_food"},
        {value: 'Pet Care', key: 'Pet Care', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: 'Stationery', key: 'Stationery', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
    ],
    "Beauty & Personal Care": [
        {value: "Bath & Body", key: "Bath & Body", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Feminine Care", key: "Feminine Care", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Fragrance", key: "Fragrance", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Hair Care", key: "Hair Care", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Make Up", key: "Make Up", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Men's Grooming", key: "Men's Grooming", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Oral Care", key: "Oral Care", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Skin Care", key: "Skin Care", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Maternity Care", key: "Maternity Care", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Baby Care", key: "Baby Care", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Nursing & Feeding", key: "Nursing & Feeding", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Sexual Wellness & Sensuality", key: "Sexual Wellness & Sensuality", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Tools & Accessories", key: "Tools & Accessories", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
    ],
    "Fashion": [
        {value: "Men's Fashion Accessories", key: "Men's Fashion Accessories", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Men's Footwear Accessories", key: "Men's Footwear Accessories", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Men's Topwear", key: "Men's Topwear", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Men's Bottomwear", key: "Men's Bottomwear", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Men's Innerwear & Sleepwear", key: "Men's Innerwear & Sleepwear", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Men's Bags & Luggage", key: "Men's Bags & Luggage", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Men's Eyewear", key: "Men's Eyewear", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Men's Footwear", key: "Men's Footwear", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Men's Jewellery", key: "Men's Jewellery", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Women's Fashion Accessories", key: "Women's Fashion Accessories", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Women's Footwear Accessories", key: "Women's Footwear Accessories", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Women's Indian & Fusion Wear", key: "Women's Indian & Fusion Wear", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Women's Western Wear", key: "Women's Western Wear", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Women's Lingerie & Sleepwear", key: "Women's Lingerie & Sleepwear", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Women's Bags & Luggage", key: "Women's Bags & Luggage", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Women's Eyewear", key: "Women's Eyewear", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Women's Footwear", key: "Women's Footwear", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Women's Jewellery", key: "Women's Jewellery", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Boy's Clothing", key: "Boy's Clothing", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Boy's Footwear", key: "Boy's Footwear", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Girl's Clothing", key: "Girl's Clothing", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Girl's Footwear", key: "Girl's Footwear", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Infant's Wear", key: "Infant's Wear", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Infant Care & Accessories", key: "Infant Care & Accessories", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Infant Feeding & Nursing Essentials", key: "Infant Feeding & Nursing Essentials", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Infant Bath Accessories", key: "Infant Bath Accessories", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Infant Health & Safety", key: "Infant Health & Safety", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Infant Diapers & Toilet Training", key: "Infant Diapers & Toilet Training", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Kid's Towels & Wrappers", key: "Kid's Towels & Wrappers", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Kid's Fashion Accessories", key: "Kid's Fashion Accessories", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Kid's Jewellery", key: "Kid's Jewellery", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "Kid's Eyewear", key: "Kid's Eyewear", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: "kids Kid's Bags & Luggage", key: "Kid's Bags & Luggage", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
    ],
    "Home & Decor": [
        {value: 'Home Decor', key: 'Home Decor', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: 'Home Furnishings', key: 'Home Furnishings', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: 'Furniture', key: 'Furniture', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: 'Garden and Outdoor Products', key: 'Garden and Outdoor Products', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: 'Home Improvement', key: 'Home Improvement', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: 'Cookware and Dining', key: 'Cookware and Dining', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {value: 'torage and Organisation', key: 'Storage and Organisation', protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
    ],
    "F&B": [
        {value: 'Continental', key: 'Continental', protocolKey: ''},
        {value: 'Middle Eastern', key: 'Middle Eastern', protocolKey: ''},
        {value: 'North Indian', key: 'North Indian', protocolKey: ''},
        {value: 'Pan-Asian', key: 'Pan-Asian', protocolKey: ''},
        {value: 'Regional Indian', key: 'Regional Indian', protocolKey: ''},
        {value: 'South Indian', key: 'South Indian', protocolKey: ''},
        {value: 'Tex-Mexican', key: 'Tex-Mexican', protocolKey: ''},
        {value: 'World Cuisines', key: 'World Cuisines', protocolKey: ''},
        {value: 'Healthy Food', key: 'Healthy Food', protocolKey: ''},
        {value: 'Fast Food', key: 'Fast Food', protocolKey: ''},
        {value: 'Desserts', key: 'Desserts', protocolKey: ''},
        {value: 'Bakes & Cakes', key: 'Bakes & Cakes', protocolKey: ''},
        {value: 'Beverages (MTO)', key: 'Beverages (MTO)', protocolKey: ''},
    ],
    "Electronics": [
        {value: "Audio", key: "Audio", protocolKey: ""},
        {value: "Camera and Camcorder",key: "Camera and Camcorder", protocolKey: ""},
        {value: "Computer Peripheral", key: "Computer Peripheral", protocolKey: ""},
        {value: "Desktop and Laptop", key: "Desktop and Laptop", protocolKey: ""},
        {value: "Earphone", key: "Earphone", protocolKey: ""},
        {value: "Gaming", key: "Gaming", protocolKey: ""},
        {value: "Headphone", key: "Headphone", protocolKey: ""},
        {value: "Mobile Phone", key: "Mobile Phone", protocolKey: ""},
        {value: "Mobile Accessories", key: "Mobile Accessories", protocolKey: ""},
        {value: "Safety Security", key: "Safety Security", protocolKey: ""},
        {value: "Smart Watches", key: "Smart Watches", protocolKey: ""},
        {value: "Speaker", key: "Speaker", protocolKey: ""},
        {value: "Television", key: "Television", protocolKey: ""},
        {value: "Video", key: "Video", protocolKey: ""},
        {value: "Air Conditioning and Air Cleaners", key: "Air Conditioning and Air Cleaners", protocolKey: ""},
        {value: "Health, Home and Personal Care", key: "Health, Home and Personal Care", protocolKey: ""},
        {value: "Heaters", key: "Heaters", protocolKey: ""},
        {value: "Kitchen Appliances", key: "Kitchen Appliances", protocolKey: ""},
        {value: "Lighting & Electric Fans", key: "Lighting & Electric Fans", protocolKey: ""},
        {value: "Refrigerators and Freezers", key: "Refrigerators and Freezers", protocolKey: ""},
        {value: "Vacuum Cleaners", key: "Vacuum Cleaners", protocolKey: ""},
        {value: "Washing Machines and Accessories", key: "Washing Machines and Accessories", protocolKey: ""},
        {value: "Water Purifiers and Coolers", key: "Water Purifiers and Coolers", protocolKey: ""},
        {value: "Inverter & Stabilizer", key: "Inverter & Stabilizer", protocolKey: ""
        }
      ],
    "Health & Wellness": [
        {key: "Pain Relieving Ointments", value: "Pain Relieving Ointments", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {key: "Nutrition and Supplements", value: "Nutrition and Supplements", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {key: "Personal and Baby Care", value: "Personal and Baby Care", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {key: "Sexual Wellness", value: "Sexual Wellness", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {key: "Gastric and Other Concerns", value: "Gastric and Other Concerns", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {key: "Covid Essentials", value: "Covid Essentials", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {key: "Diabetes Control", value: "Diabetes Control", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"},
        {key: "Health Devices", value: "Health Devices", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities"}
      ]
};

export const FIELD_NOT_ALLOWED_BASED_ON_PROTOCOL_KEY = {
    "@ondc/org/mandatory_reqs_veggies_fruits": ["manufacturerOrPackerName", "manufacturerOrPackerAddress", "commonOrGenericNameOfCommodity", "monthYearOfManufacturePackingImport", "nutritionalInfo", "additiveInfo", 'importerFSSAILicenseNo', "brandOwnerFSSAILicenseNo"],
    "@ondc/org/statutory_reqs_packaged_commodities": ["nutritionalInfo", "additiveInfo", "importerFSSAILicenseNo", "brandOwnerFSSAILicenseNo"],
    "@ondc/org/statutory_reqs_prepackaged_food": ["manufacturerOrPackerName", "manufacturerOrPackerAddress", "commonOrGenericNameOfCommodity", "monthYearOfManufacturePackingImport"],
};